// <auto-generated />
using AutobuskaStanica.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutobuskaStanica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230911212248_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutobuskaStanica.Model.Karta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("br_sedista")
                        .HasColumnType("int");

                    b.Property<int>("cena")
                        .HasColumnType("int");

                    b.Property<int>("polazak_id")
                        .HasColumnType("int");

                    b.Property<int>("povratnakarta_id")
                        .HasColumnType("int");

                    b.Property<int>("putnik_id")
                        .HasColumnType("int");

                    b.Property<string>("tipkarte")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("karta", (string)null);
                });

            modelBuilder.Entity("AutobuskaStanica.Model.Polazak", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("datum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grad_odrediste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grad_polazak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kilometraza")
                        .HasColumnType("int");

                    b.Property<string>("prevoznik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("polazak", (string)null);
                });

            modelBuilder.Entity("AutobuskaStanica.Model.Povratnakarta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("polazak_id")
                        .HasColumnType("int");

                    b.Property<int>("putnik_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("povratnakarta", (string)null);
                });

            modelBuilder.Entity("AutobuskaStanica.Model.Putnik", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("god_rodj")
                        .HasColumnType("int");

                    b.Property<string>("ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("putnik", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
